apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
  labels:
    app: CHANGE-ME-devnet # TODO: Change me
  name: CHANGE-ME-devnet # TODO: Change me
  namespace: default
  resourceVersion: "65918483"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: CHANGE-ME-devnet # TODO: Change me
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: CHANGE-ME-devnet # TODO: Change me
    spec:
      containers:
        - env:
            - name: ENVIROMENT
              value: 'development'
            - name: DIALECT_SDK_ENVIROMENT
              value: 'development'
            - name: DIALECT_SDK_SOLANA_NETWORK_NAME
              value: 'devnet'
            - name: DIALECT_SDK_SOLANA_RPC_URL
              valueFrom:
                secretKeyRef:
                  key: DEVNET_RPC_URL
                  name: env-vars
            - name: DIALECT_SDK_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: CHANGE-ME_MESSAGING_PRIVATE_KEY_DEVNET # TODO: Change me
                  name: env-vars
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  key: TWILIO_ACCOUNT_SID
                  name: env-vars
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWILIO_AUTH_TOKEN
                  name: env-vars
            - name: TWILIO_SMS_SENDER
              value: "+15613366687"
            - name: SENDGRID_KEY
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: env-vars
            - name: SENDGRID_EMAIL
              value: "hello@dialect.to"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_TOKEN
                  name: env-vars
          image: dialectlab/CHANGE-ME:0.1.0 # TODO: Change me
          imagePullPolicy: Always
          name: CHANGE-ME-devnet
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
