name: CD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service_name:
        required: true
        type: string
      service_image_tag:
        required: true
        type: string
    secrets:
      api_github_token:
        required: true

env:
  DEPLOYMENT_SCRIPTS_REPO: dialectlabs/infrastructure

jobs:
  deployment:
    name: Create deployment PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DEPLOYMENT_SCRIPTS_REPO }}
          token: ${{ secrets.api_github_token }}
          path: ${{ env.DEPLOYMENT_SCRIPTS_REPO }}
      - name: Set service name
        id: service-name
        run: |
          echo "::set-output name=service_name::$(echo ${{ inputs.service_name }} | sed s/-/_/g)"
      - name: Install hcledit
        run: |
          curl -L https://github.com/minamijoyo/hcledit/releases/download/v0.2.5/hcledit_0.2.5_linux_amd64.tar.gz | tar -xz
          chmod +x ./hcledit
      - name: Create version file
        id: create-version-file
        env:
          ENVIRONMENT_DIR: "terraform-plans/environments/${{ inputs.environment }}"
          SERVICE_RESOURCES_FILE: "terraform-plans/environments/${{ inputs.environment }}/svc-${{ inputs.service_name }}.tf"
        run: |
          mkdir -p ${{ env.ENVIRONMENT_DIR }}
          cat ${{ env.DEPLOYMENT_SCRIPTS_REPO }}/${{ env.SERVICE_RESOURCES_FILE }} |\
          ./hcledit attribute set locals.svc_${{ steps.service-name.outputs.service_name }}_image_version '"${{ inputs.service_image_tag }}"' \
          > ${{ env.SERVICE_RESOURCES_FILE }}
      - name: Create deployment pull request
        env:
          API_TOKEN_GITHUB: ${{ secrets.api_github_token }}
          INPUT_SOURCE_FOLDER: "terraform-plans"
          INPUT_DESTINATION_REPO: ${{ env.DEPLOYMENT_SCRIPTS_REPO }}
          INPUT_DESTINATION_BASE_BRANCH: "main"
          INPUT_DESTINATION_HEAD_BRANCH: cd/${{ inputs.environment }}/${{ github.event.repository.name }}/${{ inputs.service_image_tag }}
          INPUT_USER_EMAIL: ${{ github.event.pusher.email }}
          INPUT_USER_NAME: ${{ github.actor }}
        run: "${GITHUB_WORKSPACE}/.github/create-pr.sh"
